project:
  output-dir: docs/
  type: website

website:
  title: "Phần mềm hữu ích"
  favicon: logor.png
  navbar:
    logo: logor.png    
    right:
      - about.qmd
      - icon: house-door-fill
        href: https://www.tuhocr.com/
      - icon: github
        href: https://github.com/tuhocr/phanmemhuuich
format:
  html:
    toc: true
    number-sections: true
    theme:
      light: [comos, light.scss]
      dark: [solar, dark.scss]
      # - minty
      # - dark.scss
    highlight-style: 
      light: "dracula.theme"
      dark: "kate.theme"


 




